version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 761823580113.dkr.ecr.us-west-2.amazonaws.com
      - echo Logged in to Amazon ECR successfully

  build:
    commands:
      - echo Building Docker Image for Flask Application
      - docker build -t flask_image .
      - echo Image built successfully

  post_build:
    commands:
      - echo Tagging Flask Docker image
      - docker tag flask_image:latest 761823580113.dkr.ecr.us-west-2.amazonaws.com/flask_image:0.1
      - docker push 761823580113.dkr.ecr.us-west-2.amazonaws.com/flask_image:0.1
      - echo Flask image pushed to ECR